title: Adventures in Containerland
description: Just a scratchpad where I can keep track of some musings. 
remote_theme: "mmistakes/minimal-mistakes"

url: https://smarticu5.github.io/

aux_links: # remove if you don't want this link to appear on your pages
  Main: https://github.com/smarticu5/smarticu5.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

site_locale: "en-GB"
title_separator: "|"
show_date: true

twitter:
  username: "smarticu5"

author:
  name     : "Iain Smart"
  avatar   : "https://s.gravatar.com/avatar/38a37cf99e21c8c6e9a79c15ae75ab0f?s=240"
  bio      : "I do container security and write bad home automations."
  location : "Scotland"
  links:
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/smarticu5"

defaults:
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true

collections:
  talks:
    output: true
    permalink: /:collection/:path/
